import '../../api/documents/methods.js';
import '../../api/documents/server/publications.js';
import '../../api/shops/methods.js';
import '../../api/shops/server/publications.js';
import '../../api/messages/methods.js';
import '../../api/messages/server/publications.js'
import '../../api/bookings/methods.js';
import '../../api/bookings/server/publications.js';
import '../../api/reviews/methods.js';
import '../../api/reviews/server/publications.js';
